# Generated by Django 2.0.1 on 2018-01-04 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='division',
            name='name',
            field=models.CharField(default='asd', max_length=255),
            preserve_default=False,
        ),
    ]
