# Generated by Django 2.0.1 on 2018-01-04 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0002_division_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='geography',
            name='series',
            field=models.CharField(blank=True, help_text='Year of boundary series, e.g., 2016 TIGER/Line files.', max_length=4, null=True),
        ),
    ]
