# Generated by Django 2.0.1 on 2018-01-05 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0003_geography_series'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geography',
            name='effective_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='geography',
            name='effective_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
