# Generated by Django 2.0.1 on 2018-01-05 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0005_auto_20180105_0249'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='geometry',
            options={'verbose_name_plural': 'Geometries'},
        ),
        migrations.AlterField(
            model_name='geometry',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geometries', to='geography.Division'),
        ),
    ]
